### ISSUE TITLE
More detailed project description

### ISSUE THREAD

**Issue by npes-95** [kyriakouandreas/RoboticArm#3]
Add pictures, diagrams etc... to README.

- Team 4

**Comment by sharraftel** [comment]
There are more information in the wiki, and we are working on more documentation for the code, stay tuned :)

**Comment by DevGero** [comment]
There are more pictures and diagrams now. The Front README has a brief description. More descriptions can be found on individual README files through the file system of the project. And details descriptions on the wiki to avoid extended README files.
